from .kb_menu import kb_main_menu, kb_object_menu
from .kb_district import kb_district
from .kb_air_conditioning import kb_air_conditioning
from .kb_apartment_layout import kb_apartment_layout
from .kb_balcony_size import kb_balcony_size
from .kb_distance_to_metro import kb_distance_to_metro
from .kb_elevator_condition import kb_elevator_condition
from .kb_furniture import kb_furniture
from .kb_location_the_road import kb_location_the_road
from .kb_redevelopment import kb_redevelopment
from .kb_registration_date import kb_registration_date
from .kb_repair import kb_repair
from .kb_roof_condition import kb_roof_condition
from .kb_side_building import kb_side_building
from .kb_technics import kb_technics
from .kb_toilet import kb_toilet
from .kb_type_of_building import kb_type_of_building
from .kb_type_of_layout import kb_type_of_layout
from .kb_type_of_property import kb_type_of_property
from .kb_type_of_service import kb_type_of_service
from .kb_type_parking import kb_type_parking
from .kb_yes_or_no import kb_yes_or_no
