from .broker import dp
from .buy_sell import dp
from .deposit import dp
from .help import dp
from .menu import dp
from .object import dp
from .object_active import dp
from .object_delete import dp
from .object_edit import dp
from .olx import dp
from .olx_new import dp
from .olx_waiting import dp
from .prepayment import dp
from .registration import dp
from .rent_apartment import dp
from .rent_commerce import dp
from .search import dp
from .search_by_id import dp
from .search_by_number import dp
from .send_buy_apartment import dp
from .send_buy_commerce import dp
from .start import dp
from .system import dp
from .system_olx import dp
from .system_user import dp
from .system_user_add_agent import dp
from .system_user_add_manager import dp
from .system_user_delete_agent import dp
from .system_user_delete_manager import dp
from .system_user_edit_agent import dp
from .system_user_edit_manager import dp
from .system_user_show_agent import dp
from .system_user_show_manager import dp

__all__ = ["dp"]
