from .kb_appointment import kb_appointment
from .kb_business import kb_business
from .kb_completed_building import kb_completed_building
from .kb_distance_to_metro import kb_distance_to_metro
from .kb_district import kb_district
from .kb_freestanding import kb_freestanding
from .kb_furniture import kb_furniture
from .kb_infrastructure import kb_infrastructure
from .kb_location_the_road import kb_location_the_road
from .kb_menu import kb_main_menu, kb_object_menu
from .kb_non_residential import kb_non_residential
from .kb_number_of_buildings import kb_number_of_buildings
from .kb_power_supply import kb_power_supply
from .kb_repair import kb_repair
from .kb_security import kb_security
from .kb_sewerage import kb_sewerage
from .kb_side_building import kb_side_building
from .kb_system_gas import kb_system_gas
from .kb_system_heating import kb_system_heating
from .kb_technics import kb_technics
from .kb_tenants import kb_tenants
from .kb_toilet import kb_toilet
from .kb_traffic_level import kb_traffic_level
from .kb_type_of_building import kb_type_of_building
from .kb_type_parking import kb_type_parking
from .kb_yes_or_no import kb_yes_or_no
from .kb_number_floor import kb_number_floor
from .kb_number_room import kb_number_room