from aiogram.dispatcher.filters.state import State, StatesGroup


class BySell(StatesGroup):
    Deposit_Q1 = State()
    Deposit_Q2 = State()
    Deposit_Q3 = State()
    Deposit_Q4 = State()
    Deposit_Q5 = State()
    Deposit_Q6 = State()
    Deposit_Q7 = State()
    Deposit_Q8 = State()
    Deposit_Q9 = State()
    Deposit_Q10 = State()
    Deposit_Q11 = State()
    Deposit_Q12 = State()
    Deposit_Q13 = State()
    Deposit_Q14 = State()
    Deposit_Q15 = State()
    Deposit_Q16 = State()
    Registration_Q1 = State()
    Registration_Q2 = State()
    Registration_Q3 = State()
    Registration_Q4 = State()
    Registration_Q5 = State()
    Registration_Q6 = State()
    Registration_Q7 = State()
    Registration_Q8 = State()
    Registration_Q9 = State()
    Registration_Q10 = State()
    Registration_Q11 = State()
    Registration_Q12 = State()
    Registration_Q13 = State()
    Registration_Q14 = State()
    Registration_Q15 = State()
    Registration_Q16 = State()
    Registration_Q17 = State()
    Registration_Q18 = State()
    Registration_Q19 = State()
    Registration_Q20 = State()
    Registration_Q21 = State()
    Registration_Q22 = State()
    Prepayment_Q1 = State()
    Prepayment_Q2 = State()
    Prepayment_Q3 = State()
    Prepayment_Q4 = State()
    Prepayment_Q5 = State()