from aiogram.dispatcher.filters.state import State, StatesGroup


class SystemState(StatesGroup):
    Start = State()

    MainMenu = State()

    UserMenu = State()

    UserAdd = State()
    UserAddAgent_Q1 = State()
    UserAddAgent_Q2 = State()
    UserAddAgent_Q3 = State()
    UserAddAgent_Q4 = State()
    UserAddAgent_Q5 = State()
    UserAddAgent_Q6 = State()
    UserAddAgent_Q7 = State()
    UserAddAgent_Q8 = State()
    UserAddAgent_Q9 = State()
    UserAddAgent_Q10 = State()
    UserAddAgent_Q11 = State()
    UserAddManager_Q1 = State()
    UserAddManager_Q2 = State()
    UserAddManager_Q3 = State()
    UserAddManager_Q4 = State()
    UserAddManager_Q5 = State()
    UserAddManager_Q6 = State()
    UserAddManager_Q7 = State()
    UserAddManager_Q8 = State()

    UserEdit = State()
    UserEditAgent = State()
    UserEditAgent_EditParam = State()
    UserEditAgent_FirstName_Q1 = State()
    UserEditAgent_FirstName_Q2 = State()
    UserEditAgent_LastName_Q1 = State()
    UserEditAgent_LastName_Q2 = State()
    UserEditAgent_Patronymic_Q1 = State()
    UserEditAgent_Patronymic_Q2 = State()
    UserEditAgent_Date_Q1 = State()
    UserEditAgent_Date_Q2 = State()
    UserEditAgent_ResidenceArea_Q1 = State()
    UserEditAgent_ResidenceArea_Q2 = State()
    UserEditAgent_Phone_Q1 = State()
    UserEditAgent_Phone_Q2 = State()
    UserEditAgent_TelegramID_Q1 = State()
    UserEditAgent_TelegramID_Q2 = State()
    UserEditAgent_TypeOfProperty_Q1 = State()
    UserEditAgent_TypeOfProperty_Q2 = State()
    UserEditAgent_Rang_Q1 = State()
    UserEditAgent_Rang_Q2 = State()
    UserEditAgent_Sector_Q1 = State()
    UserEditAgent_Sector_Q2 = State()
    UserEditManager = State()
    UserEditManager_EditParam = State()
    UserEditManager_FirstName_Q1 = State()
    UserEditManager_FirstName_Q2 = State()
    UserEditManager_LastName_Q1 = State()
    UserEditManager_LastName_Q2 = State()
    UserEditManager_Patronymic_Q1 = State()
    UserEditManager_Patronymic_Q2 = State()
    UserEditManager_Date_Q1 = State()
    UserEditManager_Date_Q2 = State()
    UserEditManager_ResidenceArea_Q1 = State()
    UserEditManager_ResidenceArea_Q2 = State()
    UserEditManager_Phone_Q1 = State()
    UserEditManager_Phone_Q2 = State()
    UserEditManager_TelegramID_Q1 = State()
    UserEditManager_TelegramID_Q2 = State()
    UserEditExit = State()

    UserDelete = State()
    UserDeleteAgent_Q1 = State()
    UserDeleteAgent_Q2 = State()
    UserDeleteManager_Q1 = State()
    UserDeleteManager_Q2 = State()

    UserShow = State()
    UserShowAgent_Select = State()
    UserShowAgent_AllUsers = State()
    UserShowAgent_CurrentUser = State()
    UserShowManager_Select = State()
    UserShowManager_AllUsers = State()
    UserShowManager_CurrentUser = State()

    OlxStart = State()
    OLX_Q1 = State()
    OLX_Q2 = State()
    OLX_Q3 = State()
    OLX_Q4 = State()
    OLX_Q5 = State()
    OLX_Q6 = State()

    OLX_Show = State()
    OLX_Show_CurrentSector = State()
